### ISSUE TITLE
docs to pages

### ISSUE THREAD

**Issue by aherrold** [lsst-epo/example-portal#2]
On the Ed Hub page secondary link "Support" page, can you make the two docs actual pages? They really weren't intended as downloads.

**Comment by benepo** [comment]
Two docs?  Unique LSST information and...?

**Comment by aherrold** [comment]
Sorry! I crossed wires on two different issues while reading my notes.
  Issue 1: There are 2 docs on NGSS that would be more useful as pages. 

Issue 2: There is a link to a page on the Support page (NGSS tech info) that actually is a working link  but it's not obvious, since it looks identical to the 3 links above that don't work.

**Comment by aherrold** [comment]
Replied on GitHub

**Comment by benepo** [comment]
> a page on the Support page (**NGSS tech info**)

Did you mean **Unique LSST Information**?

**Comment by benepo** [comment]
@aherrold  I removed the inactive Support links.  Let me know if that was sufficient or if you want me to extract all the info in the PDF to HTML.

**Comment by aherrold** [comment]
Yes
