### ISSUE TITLE
Research page revision

### ISSUE THREAD

**Issue by aherrold** [lsst-epo/example-portal#4]
Re: the Research page, my vision was not to host a broad-based page for all types of research, but rather what was specific to student research based on LSST data. So I would envision it would be limited to what you currently have as the Students tab. I realize you may not have enough time to do substantial changes, but could you at least please try to place the following text and link on the Students page? 

Develop a tool similar to the My NASA Data design: http://mynasadata.larc.nasa.gov/high-school-students-2/
Imagine this:
"	The four domains of LSST research appear, with a brief explanation about them.
"	Students choose an area they are interested in, such as dark matter. 
"	A brief explanation of a few of the general research questions related to the topic appears. 
"	Students are directed to browse appropriate data sets, widgets and notebooks that they may use to conduct research on this topic.

**Comment by benepo** [comment]
Unfortunately this isn't a trivial mockup request.  Unlikely to happen by Saturday but I'll see what I can do.

**Comment by aherrold** [comment]
That’s fine- I just need to know what docs to create for use at the meeting if they won’t be on the web page.
